version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  dramatiq:
    build: .
    command: python -m dramatiq src.tasks
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  dramatiq-ui:
    image: ghcr.io/dramatiq/dramatiq-ui:latest
    environment:
      - DRAMATIQ_BROKER_URL=redis://redis:6379/0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
